ALTER TABLE "SyncLog" ADD COLUMN IF NOT EXISTS "emailsSaved" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SyncLog" ADD COLUMN IF NOT EXISTS "invoicesFound" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SyncLog" ADD COLUMN IF NOT EXISTS "driveUploaded" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SyncLog" ADD COLUMN IF NOT EXISTS "sheetsUpdated" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SyncLog" ADD COLUMN IF NOT EXISTS "errorsCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SyncLog" ADD COLUMN IF NOT EXISTS "scanMode" TEXT;
ALTER TABLE "SyncLog" ADD COLUMN IF NOT EXISTS "retryOfId" TEXT;
ALTER TABLE "SyncLog" ADD COLUMN IF NOT EXISTS "nextRetryAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "SyncLog_organizationId_type_status_startedAt_idx" ON "SyncLog"("organizationId", "type", "status", "startedAt");
CREATE INDEX IF NOT EXISTS "SyncLog_nextRetryAt_idx" ON "SyncLog"("nextRetryAt");
